### ISSUE TITLE
[Bug]: Not able to read Edge Gateways using terraform

### ISSUE THREAD

**Issue by amanorange** [orange-cloudavenue/terraform-provider-cloudavenue#781] opened 2024-08-01 12:54 UTC
### Terraform Core Version

8.14.0

### Cloud Avenue Provider Version

0.18.5

### Affected Resource(s)

cloudavenue_tier0_vrfs
cloudavenue_edgegateway

### Expected Behavior

We should be able to read Edge Gateways and Tier0_vrfs using terraform

### Actual Behavior

![image](https://github.com/user-attachments/assets/7fcc5fa9-312d-4bad-a46e-cab5bccc04fa)
![Edge_Gateway_error](https://github.com/user-attachments/assets/ec9cee67-ad40-4d84-b011-72ddd56bdc11)

### Relevant Error/Panic Output Snippet

```shell
│ Error: Client Error
│ 
│   with data.cloudavenue_tier0_vrfs.example,
│   on main.tf line 33, in data "cloudavenue_tier0_vrfs" "example":
│   33: data "cloudavenue_tier0_vrfs" "example" {}
│ 
│ Unable to read list T0, got error: error on list T0s: ErrorCode: -
│ ErrorReason: - ErrorMessage:External service 'infrapiextension' failed to
│ respond in the specified timeout (60 SECONDS)
╵
╷
│ Error: Error retrieving edge gateway
│ 
│   with data.cloudavenue_edgegateway.example,
│   on main.tf line 35, in data "cloudavenue_edgegateway" "example":
│   35: data "cloudavenue_edgegateway" "example" {
│ 
│ error on list edge gateways: ErrorCode: - ErrorReason: -
│ ErrorMessage:External service 'infrapiextension' failed to respond in the
│ specified timeout (60 SECONDS)
╵
ERROR: Job failed: exit code 1
```

###############################################################
###############################################################
```hcl
terraform {
  required_providers {
     cloudavenue = {
      source = "orange-cloudavenue/cloudavenue"
      version = "0.18.5"
    }

  }
}

provider "cloudavenue" {  
  org      = var.org
  user     = var.user
  password = var.password
  #url      = var.url
  vdc      = var.vdc
}
```

##############################################################
###############################################################

```
data "cloudavenue_tier0_vrfs" "example" {}

data "cloudavenue_edgegateway" "example" {
  name = "tn01i01ocb0006974spt101"
}

data "cloudavenue_network_routed" "example" {
  name            = "subnet-customer-edge"
  edge_gateway_id =  data.cloudavenue_edgegateway.example.id
}


data "cloudavenue_catalog_vapp_template" "example" {
  catalog_name  = "Orange-Linux-Internal"
  template_name = "OBSMASTER_SLES_15SP5"
}

resource "cloudavenue_vapp" "example" {
  name        = "k8s"
  description = "This is an example vApp"
}

resource "cloudavenue_vapp_org_network" "example" {
  vapp_name    = cloudavenue_vapp.example.name
  vdc         = "Edge-Computing"
  network_name = data.cloudavenue_network_routed.example.name
}

resource "cloudavenue_vm" "k8s_vm1" {
  name      = "k8s-vm1"
  vdc         = "Edge-Computing"
  vapp_name = cloudavenue_vapp.example.name
  deploy_os = {
    vapp_template_id = data.cloudavenue_catalog_vapp_template.example.id
  }
  settings = {
    guest_properties = {
      "guestinfo.hostname" = "k8s-vm1"
    }
    customization = {
      admin_password = "tttt"
      allow_local_admin_password = true
    }
  }
  resource = {
    cpus   = 4
    memory = 4096
    networks = [
      {
        type               = "org"
        name               = cloudavenue_vapp_org_network.example.network_name
        ip                 = "192.168.0.228"
        ip_allocation_mode = "MANUAL"
        is_primary         = true
      }
    ]
  }
}

resource "cloudavenue_vm" "k8s_vm2" {
  name      = "k8s-vm2"
  vdc         = "Edge-Computing"
  vapp_name = cloudavenue_vapp.example.name
  deploy_os = {
    vapp_template_id = data.cloudavenue_catalog_vapp_template.example.id
  }
  settings = {
    guest_properties = {
      "guestinfo.hostname" = "k8s-vm2"
    }
    customization = {
      admin_password = "tttt"
      allow_local_admin_password = true
    }
  }
  resource = {
    cpus   = 4
    memory = 4096
    networks = [
      {
        type               = "org"
        name               = cloudavenue_vapp_org_network.example.network_name
        ip                 = "192.168.0.229"
        ip_allocation_mode = "MANUAL"
        is_primary         = true
      }
    ]
  }
}

resource "cloudavenue_vm" "k8s_vm3" {
  name      = "k8s-vm3"
  vdc         = "Edge-Computing"
  vapp_name = cloudavenue_vapp.example.name
  deploy_os = {
    vapp_template_id = data.cloudavenue_catalog_vapp_template.example.id
  }
  settings = {
    guest_properties = {
      "guestinfo.hostname" = "k8s-vm3"
    }
    customization = {
      admin_password = "tttt"
      allow_local_admin_password = true
    }
  }
  resource = {
    cpus   = 4
    memory = 4096
    networks = [
      {
        type               = "org"
        name               = cloudavenue_vapp_org_network.example.network_name
        ip                 = "192.168.0.230"
        ip_allocation_mode = "MANUAL"
        is_primary         = true
      }
    ]
  }
}
```

### Steps to Reproduce
```
Org =  cav01iv02ocb0006974
Vdc = Edge-Computing
User = terraform
```
=================

```hcl
data "cloudavenue_tier0_vrfs" "example" {}

data "cloudavenue_edgegateway" "example" {
  name = "tn01i01ocb0006974spt101"
}
```

### Would you like to implement a fix?

None

**Comment by azrod** [comment] 2024-08-01 13:39
Hi @amanorange, 

Please try again. 

Regards

**Comment by amanorange** [comment] 2024-08-01 13:47
Hi @azrod ,

We tried it again, but still the same issue.

Just FYI.. we are using "terraform" as a service account user in our CAV environment.

╷
│ Error: Client Error
│ 
│   with data.cloudavenue_tier0_vrfs.example,
│   on main.tf line 33, in data "cloudavenue_tier0_vrfs" "example":
│   33: data "cloudavenue_tier0_vrfs" "example" {}
│ 
│ Unable to read list T0, got error: error on list T0s: ErrorCode: -
│ ErrorReason: - ErrorMessage:External service 'infrapiextension' failed to
│ respond in the specified timeout (60 SECONDS)
╵
╷
│ Error: Error retrieving edge gateway
│ 
│   with data.cloudavenue_edgegateway.example,
│   on main.tf line 35, in data "cloudavenue_edgegateway" "example":
│   35: data "cloudavenue_edgegateway" "example" {
│ 
│ error on list edge gateways: ErrorCode: - ErrorReason: -
│ ErrorMessage:External service 'infrapiextension' failed to respond in the
│ specified timeout (60 SECONDS)
╵

**Comment by azrod** [comment] 2024-08-02 08:45
Hi, 

It already worked with a service account ?

**Comment by amanorange** [comment] 2024-08-02 09:59
Hi @azrod , 

Thanks a lot.
Yes, it started to work today morning .

Can you please let us know what exactly the issue was ? , as we were facing the issue since last 1 week :) . 

Best Regards,
Aman

**Comment by azrod** [comment] 2024-08-02 11:12
Hi,

There was a problem with the API. 
The problem is now fixed.

**Closed by azrod** 2024-08-02 11:12 UTC
Labels: bug, community

**Comment by jcnaud** [comment] 2024-08-05 13:28
Hello,

This morning, yes it worked with the new version 0.19.0 cloud avenue provider.

But this afternoon, the timeout out come back.

![Capture](https://github.com/user-attachments/assets/bd173907-0147-4731-ad98-7a5aacbb9271)

I use Terraform with service account on https://console2.cloudavenue.orange-business.com

I think, the API issue come back.

Regards.

**Comment by jcnaud** [comment] 2024-08-06 07:25
Hi,

It's good, the API is operational again this morning.

Regards
