### ISSUE TITLE
[Bug]: VM Disk Creation error

### ISSUE THREAD

**Issue by MAE-orange** [orange-cloudavenue/terraform-provider-cloudavenue#741] opened 2024-03-04 14:53 UTC
### Terraform Core Version

v1.5.7

### Cloud Avenue Provider Version

v0.18.2

### Affected Resource(s)

CloudAvenue Disk 
Cloudavenue VM

### Expected Behavior

Disk and vm creation

### Actual Behavior

We realize test of VM production into cloud avenue, We can produce vm but there are exception with disk attachment. It’s strange because in theory we request scsi a the creation – first plan, indicates :
```
+ create
<= read (data resources)
Terraform will perform the following actions:
# module.disk.cloudavenue_vm_disk.disk will be created
+ resource "cloudavenue_vm_disk" "disk" {
+ bus_number = 1
+ bus_type = "SCSI"
+ id = (known after apply)
+ is_detachable = true
+ name = "diskHicham"
+ size_in_mb = 204800
+ storage_profile = "silver"
+ unit_number = 1
+ vapp_name = "VappHicham"
+ vdc = (known after apply)
+ vm_name = "VmHicham"
}
```

The Vm is built but into terraform pipeline if fails on disk part after

```
module.vm.cloudavenue_vm.res_vm: Still creating... [4m40s elapsed]
module.vm.cloudavenue_vm.res_vm: Still creating... [4m50s elapsed]
module.vm.cloudavenue_vm.res_vm: Creation complete after 4m57s [id=urn:vcloud:vm:005fc058-f1d6-4a42-b4e9-1f869e00a712]
module.disk.cloudavenue_vm_disk.disk: Creating...
module.disk.cloudavenue_vm_disk.disk: Still creating... [10s elapsed]
module.disk.cloudavenue_vm_disk.disk: Still creating... [20s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.disk.cloudavenue_vm_disk.disk, provider
│ "provider[\"registry.terraform.io/orange-cloudavenue/cloudavenue\"]"
│ produced an unexpected new value: .bus_type: was cty.StringVal("SCSI"), but
│ now cty.StringVal("SATA").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Releasing state lock. This may take a few moments...
Uploading artifacts for failed job
```

If we realize a plan after this creation, it indicates

```
module.disk.cloudavenue_vm_disk.disk: Refreshing state... [id=urn:vcloud:disk:9ea77604-ceeb-428b-a3ab-d2b7146c4570]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:
# module.disk.cloudavenue_vm_disk.disk has changed
~ resource "cloudavenue_vm_disk" "disk" {
~ bus_type = "SATA" -> "SCSI"
id = "urn:vcloud:disk:9ea77604-ceeb-428b-a3ab-d2b7146c4570"
name = "diskHicham"
# (8 unchanged attributes hidden)
}
Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
─────────────────────────────────────────────────────────────────────────────
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
# module.disk.cloudavenue_vm_disk.disk is tainted, so must be replaced
-/+ resource "cloudavenue_vm_disk" "disk" {
~ id = "urn:vcloud:disk:9ea77604-ceeb-428b-a3ab-d2b7146c4570" -> (known after apply)
name = "diskHicham"
~ vdc = "obsitlabiaas" -> (known after apply)
# (8 unchanged attributes hidden)
}
Plan: 1 to add, 0 to change, 1 to destroy.

```
It seem that during the first creation, it’s automatically forced to SATA – 
And our side SATA is a problem with Ubuntu VM because we have problem of reboot with this kind of disk
And it’s the reason that we want to use “SCSI”

After many retries we face the same problem in ou pipeline but the disk could be created in terraform :

![image](https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/assets/162144538/75ddd8e3-558a-46cc-8f7b-a822c7e1c0ba)

The disk is produced as scsi but on terraform part there are error during the execution
It returns
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.disk.cloudavenue_vm_disk.disk, provider
│ "provider[\"registry.terraform.io/orange-cloudavenue/cloudavenue\"]"
│ produced an unexpected new value: .bus_type: was cty.StringVal("SCSI"), but
│ now cty.StringVal("SATA").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

```
And when we execute the plan after vm creation, it said the need of change

It’s the reason of our ticket because terraform result is not good as expected

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.disk.cloudavenue_vm_disk.disk, provider
│ "provider[\"registry.terraform.io/orange-cloudavenue/cloudavenue\"]"
│ produced an unexpected new value: .bus_type: was cty.StringVal("SCSI"), but
│ now cty.StringVal("SATA").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

```hcl
### Terraform Configuration Files

terraform {
  required_providers {
    cloudavenue = {
      source  = "orange-cloudavenue/cloudavenue"
      version = ">= 0.18.2"
    }
}

  backend "http" {}

}


module "vapp" {
  source = "gitlab.tech.orange/parent-factory/vapp/cloudavenue"
  version = "2.1.1"

  name = var.vapp_name
  description = var.vapp_description

  lease = {
    runtime_lease_in_sec = var.runtime_lease_in_sec
    storage_lease_in_sec = var.storage_lease_in_sec
  }
  
  
  networks = var.networkname
  
}



module "vm" {
  source = "gitlab.tech.orange/parent-factory/vm-linux/cloudavenue"
  version = "1.0.1"

  vapp_name = module.vapp.name
  vm_name = var.vm_name
  catalog_name = var.catalog_name
  os = var.os
  vm_resource_settings_os_type = var.os_type
  vm_resource_settings_expose_hardware_virtualization = var.expose_hardware_virtualization
  cpu = var.cpu
  cpu_cores = var.cpu_cores
  memory = var.memory

  vm_resource_settings_customization_admin_password = var.admin_password
  vm_resource_settings_customization_allow_local_admin_password = var.allow_local_admin_password
  vm_resource_settings_customization_enabled = var.enabled
  vm_resource_settings_customization_force = var.force
  vm_resource_settings_customization_init_script = var.vm_resource_settings_customization_init_script
  
  vm_resource_networks = [
    {
      type = "org"
      adapter_type = "VMXNET3" 
      ip_allocation_mode = "POOL"
      connected = var.ip_connected
      name = var.vm_network_name
      is_primary = true
    }
  ]
  depends_on = [
    module.vapp
  ]
}

module "disk" {
  source = "gitlab.tech.orange/parent-factory/disk/cloudavenue"
  version = "1.0.2"

  size_in_gb      = var.disk_size_in_gb 
  is_detachable   = var.disk_is_detachable
  name            = var.disk_name
  storage_profile = var.storage_profile
  #vapp_id         = module.vapp.id
  vapp_name       = module.vapp.name
  vm_name         = module.vm.vm_name
  bus_type        = var.bus_type
  bus_number      = var.bus_number
  unit_number     = var.unit_number

  depends_on = [
    module.vm
  ]
}
```

### Steps to Reproduce

Gitlab-ci file containing the init -plan - and run and destory

### Would you like to implement a fix?

None

**Comment by azrod** [comment] 2024-03-27 07:44
Hi @MAE-orange,

Your issue has been fixed in the release [v0.18.4](https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/releases/tag/v0.18.4) 🚀

**Comment by xriot2** [comment] 2024-04-15 13:48
Hi, I've tested it today in version v0.18.4
the problem is always present

cloudavenue_vm_disk.disk[0]: Creating...
cloudavenue_vm_disk.disk[0]: Still creating... [10s elapsed]
cloudavenue_vm_disk.disk[0]: Still creating... [20s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudavenue_vm_disk.disk[0], provider
│ "provider[\"registry.terraform.io/orange-cloudavenue/cloudavenue\"]"
│ produced an unexpected new value: .bus_type: was cty.StringVal("SCSI"), but
│ now cty.StringVal("SATA").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by azrod** [comment] 2024-08-02 09:18
Duplicate #756

**Closed by azrod** 2024-08-02 09:18 UTC
Labels: bug, community
